//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDCOLAdvanceModule.Context.AdvanceModuleQueryContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advance_VW_GetPendingExpenseReport
    {
        public Nullable<System.Guid> Id { get; set; }
        public string EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public string RankName { get; set; }
        public Nullable<decimal> RankId { get; set; }
        public Nullable<decimal> DepartmentId { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<long> BaseAdvanceCategoryId { get; set; }
        public string BaseAdvanceCategoryName { get; set; }
        public Nullable<long> AdvanceCategoryId { get; set; }
        public string AdvanceCategoryName { get; set; }
        public long ExpenseId { get; set; }
        public System.DateTime ExpenseEntryDate { get; set; }
        public string ExpensePurpose { get; set; }
        public Nullable<decimal> ExpenseAmount { get; set; }
        public Nullable<double> ExpenseAmountInBDT { get; set; }
        public double ExpenseConversionRate { get; set; }
        public string ExpenseCurrency { get; set; }
        public Nullable<System.DateTime> ExpenseApprovalDate { get; set; }
        public string ExpenseApprovalLevelName { get; set; }
        public Nullable<long> ExpenseStatusId { get; set; }
        public string ExpenseStatus { get; set; }
        public string ExpensePlaceOfOccurrance { get; set; }
        public int ExpenseDaysCount { get; set; }
    }
}
