//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDCOLAdvanceModule.Context.AdvanceModuleQueryContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advance_VW_GetRequisitionSignatory
    {
        public Nullable<System.Guid> Id { get; set; }
        public long RequisitionId { get; set; }
        public string LevelName { get; set; }
        public string SignatoryName { get; set; }
        public string SignatoryDesignation { get; set; }
    }
}
