//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDCOLAdvanceModule.Context.AdvanceModuleQueryContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advance_VW_GetHeadOfDepartment
    {
        public Nullable<System.Guid> Id { get; set; }
        public string HeadOfDepartmentUserName { get; set; }
        public string HeadOfDepartmentFullName { get; set; }
        public Nullable<decimal> DepartmentID { get; set; }
        public string DepartmentName { get; set; }
        public long HODId { get; set; }
    }
}
