//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDCOLAdvanceModule.Context.AdvanceModuleQueryContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advance_VW_GetApprovalLevelMember
    {
        public Nullable<System.Guid> Id { get; set; }
        public long ApprovalLevelMemberId { get; set; }
        public long ApprovalLevelId { get; set; }
        public int PriorityOrder { get; set; }
        public bool IsDeleted { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string EmployeeID { get; set; }
        public string EmployeeFullName { get; set; }
        public string EmployeeUserName { get; set; }
        public Nullable<decimal> RankID { get; set; }
        public string RankName { get; set; }
        public string EmployeeEmail { get; set; }
    }
}
