//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDCOLAdvanceModule.Context.AdvanceModuleQueryContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advance_VW_TimeLagRequisition
    {
        public long Id { get; set; }
        public string Purpose { get; set; }
        public long AdvanceCategoryId { get; set; }
        public string CategoryName { get; set; }
        public string RequesterUserName { get; set; }
        public long AdvanceRequisitionStatusId { get; set; }
        public Nullable<long> TicketId { get; set; }
        public Nullable<long> TicketApprovalLevelId { get; set; }
        public Nullable<long> TicketApprovalPanelId { get; set; }
        public Nullable<long> TicketApprovalStatusId { get; set; }
        public string TicketAuthorizedBy { get; set; }
        public Nullable<System.DateTime> TicketAuthorizedOn { get; set; }
        public Nullable<long> TrackerId { get; set; }
        public string TicketStatus { get; set; }
        public Nullable<long> TrackerPanelId { get; set; }
        public string TrackerPanelName { get; set; }
        public Nullable<long> TrackerLevelId { get; set; }
        public string TrackerLevelName { get; set; }
        public Nullable<long> TrackerApprovalStatusId { get; set; }
        public string TrackerStatusName { get; set; }
        public string TrackerNarration { get; set; }
        public string TrackerAuthorizedBy { get; set; }
        public Nullable<System.DateTime> TrackerAuthorizedOn { get; set; }
    }
}
