//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDCOLAdvanceModule.Context.AdvanceModuleQueryContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advance_VW_GetEntitlementMappingSetting
    {
        public Nullable<System.Guid> Id { get; set; }
        public Nullable<long> HeaderId { get; set; }
        public long DetailId { get; set; }
        public string CategoryName { get; set; }
        public Nullable<long> CategoryId { get; set; }
        public Nullable<long> CostItemId { get; set; }
        public string CostItemName { get; set; }
        public Nullable<decimal> RankId { get; set; }
        public string RankName { get; set; }
        public Nullable<decimal> EntitlementAmount { get; set; }
        public bool IsFullAmountEntitlement { get; set; }
        public Nullable<bool> IsEntitlementMandatory { get; set; }
    }
}
