//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDCOLAdvanceModule.Context.AdvanceModuleQueryContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advance_VW_GetTimeLagForExpense
    {
        public Nullable<System.Guid> Id { get; set; }
        public long PanelId { get; set; }
        public string PanelName { get; set; }
        public Nullable<long> LevelId { get; set; }
        public string LevelName { get; set; }
        public Nullable<long> ExpenseId { get; set; }
        public string ExpenseNo { get; set; }
        public Nullable<long> AdvanceCategoryId { get; set; }
        public string CategoryName { get; set; }
        public Nullable<int> PendingDays { get; set; }
        public Nullable<double> AdvanceAmountInBDT { get; set; }
        public double ExpenseAmountInBDT { get; set; }
        public string RequesterUserName { get; set; }
        public string EmployeeID { get; set; }
        public string EmployeeName { get; set; }
    }
}
