//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDCOLAdvanceModule.Context.AdvanceModuleQueryContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advance_VW_GetAdvanceExpense
    {
        public Nullable<System.Guid> Id { get; set; }
        public string RequesterUserName { get; set; }
        public string EmployeeName { get; set; }
        public long HeaderId { get; set; }
        public string ExpenseNo { get; set; }
        public Nullable<long> ExpenseApprovalTicketId { get; set; }
        public Nullable<long> ApprovalStatusId { get; set; }
        public Nullable<System.DateTime> AuthorizedOn { get; set; }
        public long AdvanceCategoryId { get; set; }
        public string AdvanceCategoryName { get; set; }
        public Nullable<bool> IsCeilingApplicable { get; set; }
        public Nullable<decimal> CeilingAmount { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public string Currency { get; set; }
        public double ConversionRate { get; set; }
        public double NoOfDays { get; set; }
        public string Purpose { get; set; }
        public System.DateTime ExpenseEntryDate { get; set; }
        public long AdvanceExpenseStatusId { get; set; }
        public string AdvanceExpenseStatusName { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public bool IsDeleted { get; set; }
        public string RecommendedBy { get; set; }
        public Nullable<System.DateTime> RecommendedOn { get; set; }
        public Nullable<decimal> EmployeeDepartmentID { get; set; }
        public string EmployeeDepartmentName { get; set; }
        public Nullable<decimal> EmployeeRankID { get; set; }
        public string EmployeeRankName { get; set; }
        public decimal AdvanceAmount { get; set; }
        public double AdvanceAmountInBDT { get; set; }
        public decimal ExpenseAmount { get; set; }
        public double ExpenseAmountInBDT { get; set; }
        public bool IsPaid { get; set; }
        public string PaidBy { get; set; }
        public Nullable<System.DateTime> ExpenseIssueDate { get; set; }
        public Nullable<double> NoOfUnit { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public Nullable<decimal> TotalRevenue { get; set; }
        public string AdvanceCorporateRemarks { get; set; }
        public string RejectedBy { get; set; }
        public Nullable<System.DateTime> RejectedOn { get; set; }
        public bool IsReceived { get; set; }
        public string ReceivedBy { get; set; }
        public Nullable<System.DateTime> ReceivedOn { get; set; }
    }
}
