// <auto-generated />
namespace IDCOLAdvanceModule.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Vendor_Renamed_ThirdPartyReceipient : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Vendor_Renamed_ThirdPartyReceipient));
        
        string IMigrationMetadata.Id
        {
            get { return "201702270422080_Vendor_Renamed_ThirdPartyReceipient"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
