// <auto-generated />
namespace IDCOLAdvanceModule.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CountryName_Added_In_AdvanceOverseasTravelRequisitionHeader : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CountryName_Added_In_AdvanceOverseasTravelRequisitionHeader));
        
        string IMigrationMetadata.Id
        {
            get { return "201702280449052_CountryName_Added_In_AdvanceOverseasTravelRequisitionHeader"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
