// <auto-generated />
namespace IDCOLAdvanceModule.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RejectedOn_RejectedBy_Added_in_AdvanceRequisitionHeader : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RejectedOn_RejectedBy_Added_in_AdvanceRequisitionHeader));
        
        string IMigrationMetadata.Id
        {
            get { return "201703040614082_RejectedOn_RejectedBy_Added_in_AdvanceRequisitionHeader"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
