// <auto-generated />
namespace IDCOLAdvanceModule.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FromCurrency_And_ToCurrency_Made_String : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FromCurrency_And_ToCurrency_Made_String));
        
        string IMigrationMetadata.Id
        {
            get { return "201702261043588_FromCurrency_And_ToCurrency_Made_String"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
