// <auto-generated />
namespace IDCOLAdvanceModule.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class BankId_BranchId_Nullable_in_VoucherHeader : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BankId_BranchId_Nullable_in_VoucherHeader));
        
        string IMigrationMetadata.Id
        {
            get { return "201703281442543_BankId_BranchId_Nullable_in_VoucherHeader"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
