// <auto-generated />
namespace IDCOLAdvanceModule.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Rename_PanelType_To_ApprovalPanelType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Rename_PanelType_To_ApprovalPanelType));
        
        string IMigrationMetadata.Id
        {
            get { return "201701301222239_Rename_PanelType_To_ApprovalPanelType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
