// <auto-generated />
namespace IDCOLAdvanceModule.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class one_expense_multiple_requisition : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(one_expense_multiple_requisition));
        
        string IMigrationMetadata.Id
        {
            get { return "201703270435156_one_expense_multiple_requisition"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
