// <auto-generated />
namespace IDCOLAdvanceModule.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RequisitionFile_ExpenseFile_ModelAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RequisitionFile_ExpenseFile_ModelAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "201703080541112_RequisitionFile_ExpenseFile_ModelAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
