// <auto-generated />
namespace IDCOLAdvanceModule.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class HistoryModels_Added_For_Expense : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HistoryModels_Added_For_Expense));
        
        string IMigrationMetadata.Id
        {
            get { return "201704010504128_HistoryModels_Added_For_Expense"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
