// <auto-generated />
namespace IDCOLAdvanceModule.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_FourColumns_In_AdvanceTravelRequisitionHeader : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_FourColumns_In_AdvanceTravelRequisitionHeader));
        
        string IMigrationMetadata.Id
        {
            get { return "201702221345362_Add_FourColumns_In_AdvanceTravelRequisitionHeader"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
