// <auto-generated />
namespace IDCOLAdvanceModule.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SentDate_Added_ExpenseVoucherDetail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SentDate_Added_ExpenseVoucherDetail));
        
        string IMigrationMetadata.Id
        {
            get { return "201704181253180_SentDate_Added_ExpenseVoucherDetail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
