// <auto-generated />
namespace IDCOLAdvanceModule.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Alter_SQLVIEW_Advance_VW_GetAdvanceExpenseDetail_Justification : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Alter_SQLVIEW_Advance_VW_GetAdvanceExpenseDetail_Justification));
        
        string IMigrationMetadata.Id
        {
            get { return "201706010801049_Alter_SQLVIEW_Advance_VW_GetAdvanceExpenseDetail_Justification"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
