// <auto-generated />
namespace IDCOLAdvanceModule.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SQLVIEW_Add_Advance_VW_GetRejectedRequisitionReport : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SQLVIEW_Add_Advance_VW_GetRejectedRequisitionReport));
        
        string IMigrationMetadata.Id
        {
            get { return "201703050947466_SQLVIEW_Add_Advance_VW_GetRejectedRequisitionReport"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
