// <auto-generated />
namespace IDCOLAdvanceModule.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ColumnAdded_AdvanceTravelExpenseDetails : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ColumnAdded_AdvanceTravelExpenseDetails));
        
        string IMigrationMetadata.Id
        {
            get { return "201702221029258_ColumnAdded_AdvanceTravelExpenseDetails"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
