// <auto-generated />
namespace IDCOLAdvanceModule.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_TotalRevenue_In_AdvanceCorporateAdvisoryRequisitionHeader : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_TotalRevenue_In_AdvanceCorporateAdvisoryRequisitionHeader));
        
        string IMigrationMetadata.Id
        {
            get { return "201704030627308_add_TotalRevenue_In_AdvanceCorporateAdvisoryRequisitionHeader"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
