// <auto-generated />
namespace IDCOLAdvanceModule.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Description_Column_Added_In_RequisitionVoucherDetail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Description_Column_Added_In_RequisitionVoucherDetail));
        
        string IMigrationMetadata.Id
        {
            get { return "201703130853428_Description_Column_Added_In_RequisitionVoucherDetail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
