// <auto-generated />
namespace IDCOLAdvanceModule.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IsFullAmountEntitlement_Added_ExecutiveOverseasTravellingAllowance : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IsFullAmountEntitlement_Added_ExecutiveOverseasTravellingAllowance));
        
        string IMigrationMetadata.Id
        {
            get { return "201704180506453_IsFullAmountEntitlement_Added_ExecutiveOverseasTravellingAllowance"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
