// <auto-generated />
namespace IDCOLAdvanceModule.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ALTER_VW_AdvanceRequisitonAndEntitleMapping : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ALTER_VW_AdvanceRequisitonAndEntitleMapping));
        
        string IMigrationMetadata.Id
        {
            get { return "201702151409382_ALTER_VW_AdvanceRequisitonAndEntitleMapping"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
