// <auto-generated />
namespace IDCOLAdvanceModule.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class destinationUser_DepartmentId_RankIdAddToRequestheader : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(destinationUser_DepartmentId_RankIdAddToRequestheader));
        
        string IMigrationMetadata.Id
        {
            get { return "201702051441361_destinationUser_DepartmentId_RankIdAddToRequestheader"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
