// <auto-generated />
namespace IDCOLAdvanceModule.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Update_AdvanceCategory_Table_Data : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_AdvanceCategory_Table_Data));
        
        string IMigrationMetadata.Id
        {
            get { return "201705280320547_Update_AdvanceCategory_Table_Data"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
