// <auto-generated />
namespace IDCOLAdvanceModule.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DiluteDesignation_Remove_AuditTrail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DiluteDesignation_Remove_AuditTrail));
        
        string IMigrationMetadata.Id
        {
            get { return "201703220933308_DiluteDesignation_Remove_AuditTrail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
