// <auto-generated />
namespace IDCOLAdvanceModule.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class OverseasExpenseHeader_OverseasExpenseDetail_Models_Added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OverseasExpenseHeader_OverseasExpenseDetail_Models_Added));
        
        string IMigrationMetadata.Id
        {
            get { return "201702241720334_OverseasExpenseHeader_OverseasExpenseDetail_Models_Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
