// <auto-generated />
namespace IDCOLAdvanceModule.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SQLVIEW_Advance_VW_GetApprovalLevelMember : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SQLVIEW_Advance_VW_GetApprovalLevelMember));
        
        string IMigrationMetadata.Id
        {
            get { return "201701311349283_SQLVIEW_Advance_VW_GetApprovalLevelMember"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
