// <auto-generated />
namespace IDCOLAdvanceModule.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IsApprovalAuthority_Added_In_ApprovalLevel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IsApprovalAuthority_Added_In_ApprovalLevel));
        
        string IMigrationMetadata.Id
        {
            get { return "201703180822148_IsApprovalAuthority_Added_In_ApprovalLevel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
