// <auto-generated />
namespace IDCOLAdvanceModule.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ApprovatTicketId_And_ApprovalLevelId_In_ApplicationNotifiation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ApprovatTicketId_And_ApprovalLevelId_In_ApplicationNotifiation));
        
        string IMigrationMetadata.Id
        {
            get { return "201704110530084_ApprovatTicketId_And_ApprovalLevelId_In_ApplicationNotifiation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
