// <auto-generated />
namespace IDCOLAdvanceModule.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Drop_Advance_VW_GetPendingRequisitionExpenseReport : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Drop_Advance_VW_GetPendingRequisitionExpenseReport));
        
        string IMigrationMetadata.Id
        {
            get { return "201703051505007_Drop_Advance_VW_GetPendingRequisitionExpenseReport"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
