// <auto-generated />
namespace IDCOLAdvanceModule.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_IsPaid_PaidBy_PaidOn_In_AdvanceExpenseHeader : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_IsPaid_PaidBy_PaidOn_In_AdvanceExpenseHeader));
        
        string IMigrationMetadata.Id
        {
            get { return "201703050432121_Add_IsPaid_PaidBy_PaidOn_In_AdvanceExpenseHeader"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
