// <auto-generated />
namespace IDCOLAdvanceModule.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class renamecolumnnameAdvanceOverseasTravelExpenseHeaderIdinCurrencyConversionRateDetail_Model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(renamecolumnnameAdvanceOverseasTravelExpenseHeaderIdinCurrencyConversionRateDetail_Model));
        
        string IMigrationMetadata.Id
        {
            get { return "201702261249356_rename column name AdvanceOverseasTravelExpenseHeaderId in CurrencyConversionRateDetail_Model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
