// <auto-generated />
namespace IDCOLAdvanceModule.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ALTERVIEW_Advance_VW_GetAdvanceExpense_Fixed_AmountInBDT : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ALTERVIEW_Advance_VW_GetAdvanceExpense_Fixed_AmountInBDT));
        
        string IMigrationMetadata.Id
        {
            get { return "201703270439508_ALTERVIEW_Advance_VW_GetAdvanceExpense_Fixed_AmountInBDT"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
