// <auto-generated />
namespace IDCOLAdvanceModule.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ExpenseNo_Added_In_AdvanceExpenseHeader : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ExpenseNo_Added_In_AdvanceExpenseHeader));
        
        string IMigrationMetadata.Id
        {
            get { return "201703101621188_ExpenseNo_Added_In_AdvanceExpenseHeader"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
