// <auto-generated />
namespace IDCOLAdvanceModule.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AccountType_AccountConfiguration_Added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AccountType_AccountConfiguration_Added));
        
        string IMigrationMetadata.Id
        {
            get { return "201703250629193_AccountType_AccountConfiguration_Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
