// <auto-generated />
namespace IDCOLAdvanceModule.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ALTER_Advance_VW_GetAdvanceExpense_Fix_ExpenseAmountInBDT_Calculation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ALTER_Advance_VW_GetAdvanceExpense_Fix_ExpenseAmountInBDT_Calculation));
        
        string IMigrationMetadata.Id
        {
            get { return "201703180456391_ALTER_Advance_VW_GetAdvanceExpense_Fix_ExpenseAmountInBDT_Calculation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
