// <auto-generated />
namespace IDCOLAdvanceModule.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SponserAmount_Added_In_Header_And_Detail_For_Local_And_OverseasTravel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SponserAmount_Added_In_Header_And_Detail_For_Local_And_OverseasTravel));
        
        string IMigrationMetadata.Id
        {
            get { return "201702280554539_SponserAmount_Added_In_Header_And_Detail_For_Local_And_OverseasTravel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
