// <auto-generated />
namespace IDCOLAdvanceModule.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PlaceOfevent_for_AdvanceMiscelleaneousExpenseHeader : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PlaceOfevent_for_AdvanceMiscelleaneousExpenseHeader));
        
        string IMigrationMetadata.Id
        {
            get { return "201702251500431_PlaceOfevent_for_AdvanceMiscelleaneousExpenseHeader"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
