// <auto-generated />
namespace IDCOLAdvanceModule.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class approvalTicket_Resolve_In_PropertyLevel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(approvalTicket_Resolve_In_PropertyLevel));
        
        string IMigrationMetadata.Id
        {
            get { return "201702230828349_approvalTicket_Resolve_In_PropertyLevel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
