// <auto-generated />
namespace IDCOLAdvanceModule.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PriorityOrder_Column_Added_In_ApprovalLevelMember : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PriorityOrder_Column_Added_In_ApprovalLevelMember));
        
        string IMigrationMetadata.Id
        {
            get { return "201705210746065_PriorityOrder_Column_Added_In_ApprovalLevelMember"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
