// <auto-generated />
namespace IDCOLAdvanceModule.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TravelSponsorFinancedDetailAmount_Added_ExpenseHistoryDetail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TravelSponsorFinancedDetailAmount_Added_ExpenseHistoryDetail));
        
        string IMigrationMetadata.Id
        {
            get { return "201704080848486_TravelSponsorFinancedDetailAmount_Added_ExpenseHistoryDetail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
