// <auto-generated />
namespace IDCOLAdvanceModule.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ALTER_SQLVW_Advance_VW_GetAdvanceRequisition_TicketApprovalStatusId_Add : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ALTER_SQLVW_Advance_VW_GetAdvanceRequisition_TicketApprovalStatusId_Add));
        
        string IMigrationMetadata.Id
        {
            get { return "201702021252109_ALTER_SQLVW_Advance_VW_GetAdvanceRequisition_TicketApprovalStatusId_Add"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
