// <auto-generated />
namespace IDCOLAdvanceModule.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ALTER_SQLVIEW_Advance_VW_GetAgingReport_Expense_ApprovedOn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ALTER_SQLVIEW_Advance_VW_GetAgingReport_Expense_ApprovedOn));
        
        string IMigrationMetadata.Id
        {
            get { return "201703190947213_ALTER_SQLVIEW_Advance_VW_GetAgingReport_Expense_ApprovedOn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
