// <auto-generated />
namespace IDCOLAdvanceModule.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ColumnNameChange_AdvanceRequisitionCategory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ColumnNameChange_AdvanceRequisitionCategory));
        
        string IMigrationMetadata.Id
        {
            get { return "201701200553154_ColumnNameChange_AdvanceRequisitionCategory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
