// <auto-generated />
namespace IDCOLAdvanceModule.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IsDeleted_Added_In_EmployeeLeave : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IsDeleted_Added_In_EmployeeLeave));
        
        string IMigrationMetadata.Id
        {
            get { return "201705161206032_IsDeleted_Added_In_EmployeeLeave"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
