// <auto-generated />
namespace IDCOLAdvanceModule.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AdvanceExpenseHeaderId_Added_In_RequisitionSourceOfFund : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AdvanceExpenseHeaderId_Added_In_RequisitionSourceOfFund));
        
        string IMigrationMetadata.Id
        {
            get { return "201703081024129_AdvanceExpenseHeaderId_Added_In_RequisitionSourceOfFund"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
