// <auto-generated />
namespace IDCOLAdvanceModule.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PanelTypes_ApprovalPanels_ApprovalLevels_ApprovalLevelForApprovalPanels_added_Initially : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PanelTypes_ApprovalPanels_ApprovalLevels_ApprovalLevelForApprovalPanels_added_Initially));
        
        string IMigrationMetadata.Id
        {
            get { return "201701291028172_PanelTypes_ApprovalPanels_ApprovalLevels_ApprovalLevelForApprovalPanels_added_Initially"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
