// <auto-generated />
namespace IDCOLAdvanceModule.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_HistoryOperationMode : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_HistoryOperationMode));
        
        string IMigrationMetadata.Id
        {
            get { return "201702020721269_Add_HistoryOperationMode"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
