// <auto-generated />
namespace IDCOLAdvanceModule.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SQLVIEW_ADD_Advance_VW_GetAdvanceRequisitionDetail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SQLVIEW_ADD_Advance_VW_GetAdvanceRequisitionDetail));
        
        string IMigrationMetadata.Id
        {
            get { return "201704021057303_SQLVIEW_ADD_Advance_VW_GetAdvanceRequisitionDetail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
