// <auto-generated />
namespace IDCOLAdvanceModule.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ALTER_Advance_VW_GetAdvanceExpense_AmountInBDT_Added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ALTER_Advance_VW_GetAdvanceExpense_AmountInBDT_Added));
        
        string IMigrationMetadata.Id
        {
            get { return "201703141751219_ALTER_Advance_VW_GetAdvanceExpense_AmountInBDT_Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
