// <auto-generated />
namespace IDCOLAdvanceModule.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ConversionRate_Currency_Added_OverseasTravelRequisitionDetail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ConversionRate_Currency_Added_OverseasTravelRequisitionDetail));
        
        string IMigrationMetadata.Id
        {
            get { return "201703051303244_ConversionRate_Currency_Added_OverseasTravelRequisitionDetail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
