//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDCOLAdvanceModule.Context.MISContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounts_ChartOfAccounts
    {
        public string AccountCode { get; set; }
        public string AccountDesc { get; set; }
        public string AccountDetails { get; set; }
        public string AccountType { get; set; }
        public string DefaultCurrencyCode { get; set; }
        public string AccountGroup { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string StructureCode { get; set; }
        public bool Status { get; set; }
        public string NormalBalance { get; set; }
        public Nullable<decimal> ProjectID { get; set; }
        public bool IsDeleted { get; set; }
        public string CashBankType { get; set; }
        public Nullable<decimal> COATypeID { get; set; }
        public Nullable<bool> IsOnBalanceSheet { get; set; }
        public Nullable<decimal> Solar_POID { get; set; }
        public Nullable<bool> IsRefinence { get; set; }
        public Nullable<decimal> Category_ID { get; set; }
        public Nullable<bool> IsDonor { get; set; }
        public Nullable<decimal> Branch_ID { get; set; }
        public bool IsVatTaxAccount { get; set; }
        public bool IsRetentionAccount { get; set; }
        public Nullable<int> VatTaxTypeId { get; set; }
    
        public virtual Loan_Bank_Branch Loan_Bank_Branch { get; set; }

        public string AccountCodeAndDescription
        {
            get
            {
                return AccountCode + " " + AccountDesc + "";
            }
        }
    }
}
