//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDCOLAdvanceModule.Context.MISContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan_Bank_Branch
    {
        public Loan_Bank_Branch()
        {
            this.Accounts_ChartOfAccounts = new HashSet<Accounts_ChartOfAccounts>();
        }
    
        public decimal Branch_ID { get; set; }
        public decimal Bank_ID { get; set; }
        public string Branch_Name { get; set; }
        public string Address { get; set; }
        public string Phone_No { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.DateTime Created_On { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Modified_On { get; set; }
        public string Modified_By { get; set; }
    
        public virtual ICollection<Accounts_ChartOfAccounts> Accounts_ChartOfAccounts { get; set; }
        public virtual Loan_Bank Loan_Bank { get; set; }
    }
}
