//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDCOLAdvanceModule.Context.MISContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan_Bank
    {
        public Loan_Bank()
        {
            this.Loan_Bank_Branch = new HashSet<Loan_Bank_Branch>();
        }
    
        public decimal Bank_ID { get; set; }
        public string Bank_Name { get; set; }
        public string Bank_Address { get; set; }
        public string Phone_No { get; set; }
        public string Email { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime Created_On { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Modified_On { get; set; }
        public string Modified_By { get; set; }
        public Nullable<bool> IsActiveForLoanDept { get; set; }
        public Nullable<bool> IsActiveForAccountsDept { get; set; }
        public Nullable<bool> IsActiveForRE { get; set; }
        public Nullable<decimal> ChequeType { get; set; }
    
        public virtual ICollection<Loan_Bank_Branch> Loan_Bank_Branch { get; set; }
    }
}
