//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDCOLAdvanceModule.Context.MISContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MISContext : DbContext
    {
        public MISContext()
            : base("name=MISContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accounts_ChartOfAccounts> Accounts_ChartOfAccounts { get; set; }
        public virtual DbSet<Accounts_FiscalYear> Accounts_FiscalYear { get; set; }
        public virtual DbSet<Admin_Office> Admin_Office { get; set; }
        public virtual DbSet<Admin_Rank> Admin_Rank { get; set; }
        public virtual DbSet<Loan_Bank> Loan_Bank { get; set; }
        public virtual DbSet<Loan_Bank_Branch> Loan_Bank_Branch { get; set; }
        public virtual DbSet<UserTable> UserTables { get; set; }
        public virtual DbSet<Accounts_NC_VendorInfo> Accounts_NC_VendorInfo { get; set; }
        public virtual DbSet<Solar_CurrencyInfo> Solar_CurrencyInfo { get; set; }
        public virtual DbSet<Admin_Departments> Admin_Departments { get; set; }
        public virtual DbSet<Accounts_NC_VatTaxCategory> Accounts_NC_VatTaxCategory { get; set; }
        public virtual DbSet<Accounts_NC_VATTAXTypeConfig> Accounts_NC_VATTAXTypeConfig { get; set; }
        public virtual DbSet<Accounts_VoucherTypes> Accounts_VoucherTypes { get; set; }
    }
}
