//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDCOLAdvanceModule.Context.MISContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTable
    {
        public UserTable()
        {
            this.UserTable1 = new HashSet<UserTable>();
        }
    
        public decimal UserId { get; set; }
        public string UserName { get; set; }
        public string NamePrefix { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string NameSuffix { get; set; }
        public string TemporaryAddress { get; set; }
        public string HomePhone { get; set; }
        public string SecondaryPhone { get; set; }
        public string SecondaryPhone2 { get; set; }
        public string SecondaryEmail { get; set; }
        public string SecondaryEmail2 { get; set; }
        public string NationalID { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<bool> IsMerried { get; set; }
        public string SpouseName { get; set; }
        public string SpousePhoneNo { get; set; }
        public Nullable<decimal> BloodGroupID { get; set; }
        public Nullable<decimal> RankID { get; set; }
        public string EmployeeID { get; set; }
        public Nullable<decimal> SupervisorID { get; set; }
        public Nullable<decimal> DepartmentID { get; set; }
        public Nullable<decimal> OfficeID { get; set; }
        public string WorkLocation { get; set; }
        public string PrimaryEmail { get; set; }
        public Nullable<decimal> Extension { get; set; }
        public string PrimaryPhone { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public string PCName { get; set; }
        public string IP { get; set; }
        public string SecretQuestion { get; set; }
        public string SecretAnswer { get; set; }
        public string Description { get; set; }
        public string Password { get; set; }
        public Nullable<int> PasswordExpirationDays { get; set; }
        public Nullable<int> PaswordInvalidAccess { get; set; }
        public bool ISDeleted { get; set; }
        public string EmeggencyContactName { get; set; }
        public string EmergencyContactAddress { get; set; }
        public string EmergencyContactPrimaryPhone { get; set; }
        public string EmergencyContactSecondaryPhone { get; set; }
        public Nullable<decimal> EmergencyContactRelationshipID { get; set; }
        public string BankAccountNumber { get; set; }
    
        public virtual Admin_Office Admin_Office { get; set; }
        public virtual Admin_Rank Admin_Rank { get; set; }
        public virtual ICollection<UserTable> UserTable1 { get; set; }
        public virtual UserTable UserTable2 { get; set; }
        public virtual Admin_Departments Admin_Departments { get; set; }

        public string FullName
        {
            get { return FirstName + " " + MiddleName + " " + LastName; }
        }
    }
}
